<?php
if($pag=='whous_page'){
testata();
navbar_gen();
echo '';
echo '<div class="bg-light">';
echo '<div class="container py-5">';
echo '<div class="row h-100 align-items-center py-5">';
echo '<div class="col-lg-6">';
echo '<h1 class="display-4">Chi Siamo</h1>';
echo '<p class="lead text-muted mb-0">Siamo un gruppo di ragazzi con un sogno: combattere l\'inquinamento e la fame nel mondo.</p>';
echo '<p class="lead text-muted">Contattaci <a href="http://dadaymattiasito.altervista.org/esame/index.php?pag=contact_page" class="text-muted">';
echo '<u>LDPcomputer</u></a>';
echo '</p>';
echo '</div>';
echo '<div class="col-lg-6 d-none d-lg-block"><img src="img/fotovarie/1.png" alt="" class="img-fluid"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="bg-white py-5">';
echo '<div class="container py-5">';
echo '<div class="row align-items-center mb-5">';
echo '<div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>';
echo '<h2 class="font-weight-light">Cosa abbiamo creato</h2>';
echo '<p class="font-italic text-muted mb-4">Con la nostra grande esperienza nell\'informatica abbiamo voluto sfruttare queste abilità per raggiungere il nostro scopo</p><a href="#" class="btn btn-light px-5 rounded-pill shadow-sm">Learn More</a>';
echo '</div>';
echo '<div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src="img/fotovarie/2.png" alt="" class="img-fluid mb-4 mb-lg-0"></div>';
echo '</div>';
echo '<div class="row align-items-center">';
echo '<div class="col-lg-5 px-5 mx-auto"><img src="img/fotovarie/4.png" alt="" class="img-fluid mb-4 mb-lg-0"></div>';
echo '<div class="col-lg-6"><i class="fa fa-leaf fa-2x mb-3 text-primary"></i>';
echo '<h2 class="font-weight-light">Il sito ha preso vita</h2>';
echo '<p class="font-italic text-muted mb-4">Ci siamo messi subito in contatto con ristoranti, farmacie, bar e negozi e abbiamo chiesto di dar in beneficienza i loro prodotti non venduti per le persone con difficoltà economiche e per le associazioni di volontariato e così abbiamo creato <span><b> il primo ecommerce dove non si spende un EURO</b></span>.</p><a href="#" class="btn btn-light px-5 rounded-pill shadow-sm">Learn More</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="bg-light py-5"  style="padding-bottom: 20px;">';
echo '<div class="container py-5">';
echo '<div class="row mb-4">';
echo '<div class="col-lg-5">';
echo '<h2 class="display-4 font-weight-light">Il nostro team</h2>';
echo '<p class="font-italic text-muted">Il nostro fantastico team uniti per un unico scopo: Combattere la povertà e la fame nelle nostre città italiane.</p>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="row text-center">';
echo '<!-- Team item-->';
echo '<div class="col-xl-3 col-sm-6 mb-5">';
echo '<div class="bg-white rounded shadow-sm py-5 px-4"><img src="img/fotovarie/3.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">';
echo '<h5 class="mb-0">Mattia Daday</h5><span class="small text-uppercase text-muted">CEO - Founder</span>';
echo '<ul class="social mb-0 list-inline mt-3">';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-facebook-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-twitter-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-instagram-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<!-- End-->';
echo '';
echo '<!-- Team item-->';
echo '<div class="col-xl-3 col-sm-6 mb-5">';
echo '<div class="bg-white rounded shadow-sm py-5 px-4"><img src="img/fotovarie/3.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">';
echo '<h5 class="mb-0">Mattia Daday</h5><span class="small text-uppercase text-muted">Project Manager</span>';
echo '<ul class="social mb-0 list-inline mt-3">';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-facebook-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-twitter-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-instagram-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<!-- End-->';
echo '';
echo '<!-- Team item-->';
echo '<div class="col-xl-3 col-sm-6 mb-5">';
echo '<div class="bg-white rounded shadow-sm py-5 px-4"><img src="img/fotovarie/3.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">';
echo '<h5 class="mb-0">Mattia Daday</h5><span class="small text-uppercase text-muted">Web Developer Full-Stack</span>';
echo '<ul class="social mb-0 list-inline mt-3">';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-facebook-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-twitter-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-instagram-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<!-- End-->';
echo '';
echo '<!-- Team item-->';
echo '<div class="col-xl-3 col-sm-6 mb-5">';
echo '<div class="bg-white rounded shadow-sm py-5 px-4"><img src="img/fotovarie/3.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">';
echo '<h5 class="mb-0">Mattia Daday</h5><span class="small text-uppercase text-muted">SEO manager</span>';
echo '<ul class="social mb-0 list-inline mt-3">';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-facebook-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-twitter-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-instagram-square"></i></a></li>';
echo '<li class="list-inline-item"><a href="#" class="social-link"><i class="fab fa-linkedin"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '<!-- End-->';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<footer class="bg-light pb-5">';
echo '<div class="container text-center">';
echo '<p><img src="img/logo/logo_small.png"  class="img-fluid"></p>';
echo '<p class="font-italic text-muted mb-0">&copy; Copyrights LDPcomputer Tutti i diritti riservati.</p>';
echo '</div>';
echo '</footer>';
closer();
}


 ?>
